Repository Vaultionizer/vault-android-app, pull requests merged in 2021-04, with the labels that each got.

#28 Create android-push-workflow.yml
  .github/workflows/android-push-workflow.yml
Labels: enhancement

#29 Replace old STOMP library with krossbow.
  .idea/codeStyles/Project.xml
  app/build.gradle
  app/src/main/java/com/vaultionizer/vaultapp/service/FileExchangeService.kt
  build.gradle
Labels: refactoring

#30 Code reformatting.
  app/src/main/java/com/vaultionizer/vaultapp/cryptography/AesCbcNopadding.kt
  app/src/main/java/com/vaultionizer/vaultapp/cryptography/AesGcmNopadding.kt
  app/src/main/java/com/vaultionizer/vaultapp/cryptography/CryptoClass.kt
  app/src/main/java/com/vaultionizer/vaultapp/cryptography/Cryptography.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/model/domain/VNFile.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/model/rest/refFile/NetworkFile.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/model/rest/refFile/NetworkFolder.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/model/rest/refFile/NetworkReferenceFile.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/model/rest/request/DeleteFileRequest.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/model/rest/request/DownloadFileRequest.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/model/rest/request/UploadFileRequest.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/model/rest/result/ApiCallFactory.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/model/rest/result/ApiResultAdapter.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/model/rest/result/ApiResultCallDecorator.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/model/rest/user/LoggedInUser.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/model/rest/user/NetworkUserAuthPair.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/source/LoginDataSource.kt
  app/src/main/java/com/vaultionizer/vaultapp/hilt/DatabaseModule.kt
  app/src/main/java/com/vaultionizer/vaultapp/hilt/RepositoryModule.kt
  app/src/main/java/com/vaultionizer/vaultapp/hilt/RestModule.kt
  app/src/main/java/com/vaultionizer/vaultapp/hilt/RetrofitModule.kt
  app/src/main/java/com/vaultionizer/vaultapp/ref-file-v1.schema.json
  app/src/main/java/com/vaultionizer/vaultapp/repository/AuthRepository.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/FileRepository.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/MiscRepository.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/ReferenceFileRepository.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/SpaceRepository.kt
  app/src/main/java/com/vaultionizer/vaultapp/service/FileService.kt
  app/src/main/java/com/vaultionizer/vaultapp/service/ReferenceFileService.kt
  app/src/main/java/com/vaultionizer/vaultapp/service/SessionService.kt
  app/src/main/java/com/vaultionizer/vaultapp/service/SpaceService.kt
  app/src/main/java/com/vaultionizer/vaultapp/service/UserService.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/auth/AuthenticationActivity.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/auth/data/AuthViewModel.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/auth/data/HostFormState.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/auth/data/UserDataFormState.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/auth/login/LoggedInUserView.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/auth/login/LoginFormState.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/auth/login/LoginFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/auth/login/LoginResult.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/auth/parts/input/HostInputFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/auth/parts/input/UserDataInputFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/auth/register/RegisterStepAuthKeyFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/auth/register/RegisterStepHostFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/auth/register/RegisterStepUserFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/MainActivity.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/file/FileAlertDialogType.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/file/FileFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/file/FileRecyclerAdapter.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/file/PathRecyclerAdapter.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/keys/KeyManagementAdapter.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/keys/KeyManagementFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/space/CreateSpaceFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/viewmodel/CreateSpaceViewModel.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/viewmodel/MainActivityViewModel.kt
  app/src/main/java/com/vaultionizer/vaultapp/util/extension/HashExtensions.kt
  app/src/main/java/com/vaultionizer/vaultapp/util/extension/RestExtension.kt
  app/src/main/java/com/vaultionizer/vaultapp/util/external/RuntimeTypeAdapterFactory.java
Labels: enhancement

#32 Fix Sonarqube workflow.
  .github/workflows/sonarqube.yml
  app/build.gradle
Labels: enhancement

#31 Implemented export and import function.
  app/src/main/java/com/vaultionizer/vaultapp/cryptography/AesCbcNopadding.kt
  app/src/main/java/com/vaultionizer/vaultapp/cryptography/AesGcmNopadding.kt
  app/src/main/java/com/vaultionizer/vaultapp/cryptography/CryptoClass.kt
  app/src/main/java/com/vaultionizer/vaultapp/cryptography/Cryptography.kt
  app/src/main/java/com/vaultionizer/vaultapp/cryptography/Hashing.kt
  app/src/main/java/com/vaultionizer/vaultapp/cryptography/dataclasses/IvCipher.kt
  app/src/main/java/com/vaultionizer/vaultapp/cryptography/dataclasses/KeySalt.kt
  app/src/main/java/com/vaultionizer/vaultapp/cryptography/dataclasses/SaltIvcipher.kt
  app/src/main/java/com/vaultionizer/vaultapp/cryptography/dataclasses/SharedKeyOutput.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/viewmodel/CreateSpaceViewModel.kt
  app/src/main/java/com/vaultionizer/vaultapp/util/Constants.kt
Labels: enhancement

#40 #VAULTIONIZER-178 Rework file exchange architecture
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/vaultionizer/vaultapp/VaultionizerApplication.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/cache/FileCache.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/db/VaultionizerLocalDatabase.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/db/dao/LocalFileDao.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/db/dao/LocalFileSyncRequestDao.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/db/dao/LocalSpaceDao.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/db/dao/relation/SpaceWithFiles.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/db/entity/LocalFile.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/db/entity/LocalFileSyncRequest.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/db/entity/converters/EnumConverters.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/model/domain/VNFile.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/model/rest/result/ManagedResult.kt
  app/src/main/java/com/vaultionizer/vaultapp/hilt/DatabaseModule.kt
  app/src/main/java/com/vaultionizer/vaultapp/hilt/RepositoryModule.kt
  app/src/main/java/com/vaultionizer/vaultapp/hilt/RestModule.kt
  app/src/main/java/com/vaultionizer/vaultapp/hilt/RetrofitModule.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/FileRepository.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/ReferenceFileRepository.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/SpaceRepository.kt
  app/src/main/java/com/vaultionizer/vaultapp/service/FileExchangeService.kt
  app/src/main/java/com/vaultionizer/vaultapp/service/SyncRequestService.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/auth/data/AuthViewModel.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/auth/login/LoginFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/file/FileFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/file/FileRecyclerAdapter.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/viewmodel/CreateSpaceViewModel.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/viewmodel/MainActivityViewModel.kt
  app/src/main/java/com/vaultionizer/vaultapp/util/Constants.kt
  app/src/main/java/com/vaultionizer/vaultapp/util/FileUtil.kt
  app/src/main/java/com/vaultionizer/vaultapp/worker/DataEncryptionWorker.kt
  app/src/main/java/com/vaultionizer/vaultapp/worker/FileUploadWorker.kt
  app/src/main/java/com/vaultionizer/vaultapp/worker/ReferenceFileSyncWorker.kt
  app/src/main/res/navigation/nav_auth.xml
  build.gradle
Labels: enhancement

#42 #VAULTIONIZER-155 Implement download feature.
  app/build.gradle
  app/src/main/java/com/vaultionizer/vaultapp/data/cache/FileCache.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/db/dao/LocalFileDao.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/db/dao/LocalFileSyncRequestDao.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/db/entity/LocalFile.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/db/entity/LocalFileSyncRequest.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/db/entity/converters/EnumConverters.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/model/domain/VNFile.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/model/rest/refFile/NetworkFolder.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/model/rest/refFile/NetworkReferenceFile.kt
  app/src/main/java/com/vaultionizer/vaultapp/hilt/RestModule.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/AuthRepository.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/FileRepository.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/SpaceRepository.kt
  app/src/main/java/com/vaultionizer/vaultapp/service/FileExchangeService.kt
  app/src/main/java/com/vaultionizer/vaultapp/service/FileService.kt
  app/src/main/java/com/vaultionizer/vaultapp/service/SyncRequestService.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/file/FileFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/viewmodel/MainActivityViewModel.kt
  app/src/main/java/com/vaultionizer/vaultapp/util/Constants.kt
  app/src/main/java/com/vaultionizer/vaultapp/util/FileUtil.kt
  app/src/main/java/com/vaultionizer/vaultapp/worker/DataEncryptionWorker.kt
  app/src/main/java/com/vaultionizer/vaultapp/worker/FileDownloadWorker.kt
  app/src/main/java/com/vaultionizer/vaultapp/worker/FileUploadWorker.kt
  app/src/main/java/com/vaultionizer/vaultapp/worker/ReferenceFileSyncWorker.kt
Labels: enhancement

#45 Include WebSocket Token as header in upload STOMP frame.
  app/src/main/java/com/vaultionizer/vaultapp/service/FileExchangeService.kt
Labels: enhancement

#44 VAULTIONIZER-193 Add tests for file cache and reference file gson.
  app/src/test/java/com/vaultionizer/vaultapp/model/ReferenceFileGsonTest.kt
  app/src/test/java/com/vaultionizer/vaultapp/model/data/FileCacheTest.kt
  app/src/test/java/com/vaultionizer/vaultapp/model/data/ReferenceFileGsonTest.kt
Labels: testing

#46 Generalize internal upload functions.
  app/src/main/java/com/vaultionizer/vaultapp/repository/FileRepository.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/viewmodel/MainActivityViewModel.kt
Labels: enhancement

#47 Fixed several bugs regarding pc.
  app/src/main/java/com/vaultionizer/vaultapp/repository/PCRepository.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/MainActivity.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/file/FileFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/pc/CreatePCFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/pc/EditPCCategoryFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/pc/EditPCCategoryParameter.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/pc/EditPCPairFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/pc/EditPCPairParameter.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/pc/InputPCNameFormState.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/pc/ViewPCFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/pc/ViewPCItemClickListener.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/pc/ViewPCRecyclerViewAdapter.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/viewmodel/CreatePCViewModel.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/viewmodel/PCViewModel.kt
  app/src/main/res/layout/create_personal_container_fragment.xml
  app/src/main/res/layout/edit_pc_category_fragment.xml
  app/src/main/res/layout/edit_pc_pair_fragment.xml
  app/src/main/res/layout/pc_category_item.xml
  app/src/main/res/layout/view_pc_category_list.xml
  app/src/main/res/navigation/nav_main.xml
Labels: enhancement

#50 VAULTIONIZER-201 Prevent multiple files with the same name in the same folder.
  app/src/main/java/com/vaultionizer/vaultapp/repository/FileRepository.kt
Labels: enhancement

#51 Improvement/test crypto
  app/src/androidTest/java/com/vaultionizer/vaultapp/cryptography/CryptographyTest.kt
  app/src/main/java/com/vaultionizer/vaultapp/cryptography/Cryptography.kt
Labels: enhancement
