Repository Vaultionizer/vault-android-app, pull requests merged in 2021-05, with the labels that each got.

#49 VAULTIONIZER-223: Remove SweetAlertDialogs library.
  app/build.gradle
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/file/FileAlertDialogType.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/file/FileFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/pc/ViewPCFragment.kt
  app/src/main/res/drawable/ic_baseline_check_white_24.xml
  app/src/main/res/drawable/ic_baseline_clear_white_24.xml
  app/src/main/res/drawable/ic_baseline_delete_outline_white_24.xml
  app/src/main/res/layout/fragment_file.xml
  app/src/main/res/values/strings.xml
Labels: DO NOT MERGE

#52 VAULTIONIZER-227: Refactor repositories so we can mock them.
  app/src/main/java/com/vaultionizer/vaultapp/data/cache/AuthCache.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/cache/FileCache.kt
  app/src/main/java/com/vaultionizer/vaultapp/hilt/CacheModule.kt
  app/src/main/java/com/vaultionizer/vaultapp/hilt/RepositoryModule.kt
  app/src/main/java/com/vaultionizer/vaultapp/hilt/RestModule.kt
  app/src/main/java/com/vaultionizer/vaultapp/hilt/RetrofitModule.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/AuthRepository.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/FileRepository.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/MiscRepository.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/PCRepository.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/PersonalContainerRepository.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/ReferenceFileRepository.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/SpaceRepository.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/SyncRequestRepository.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/impl/AuthRepositoryImpl.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/impl/FileRepositoryImpl.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/impl/MiscRepositoryImpl.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/impl/PCRepositoryImpl.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/impl/ReferenceFileRepositoryImpl.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/impl/SpaceRepositoryImpl.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/impl/SyncRequestRepositoryImpl.kt
  app/src/main/java/com/vaultionizer/vaultapp/service/FileExchangeService.kt
  app/src/main/java/com/vaultionizer/vaultapp/service/impl/FileExchangeServiceImpl.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/MainActivity.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/viewmodel/MainActivityViewModel.kt
  app/src/main/java/com/vaultionizer/vaultapp/worker/DataEncryptionWorker.kt
  app/src/main/java/com/vaultionizer/vaultapp/worker/FileDownloadWorker.kt
  app/src/main/java/com/vaultionizer/vaultapp/worker/FileUploadWorker.kt
Labels: enhancement

#53 VAULTIONIZER-206: Fix multiple download workers for one file
  app/src/main/java/com/vaultionizer/vaultapp/data/model/domain/VNFile.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/impl/FileRepositoryImpl.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/file/FileFragment.kt
Labels: enhancement

#54 Add SonarCloud badges.
  README.md
Labels: documentation

#55 Test for Android enabled. Run with: $gradlew createDebugCoverageReport
  app/build.gradle
  build.gradle
Labels: enhancement

#56 VAULTIONIZER-229: Rework deleteFile function.
  app/src/main/java/com/vaultionizer/vaultapp/data/cache/FileCache.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/db/dao/LocalFileDao.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/FileRepository.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/impl/FileRepositoryImpl.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/viewmodel/MainActivityViewModel.kt
  app/src/main/java/com/vaultionizer/vaultapp/util/Constants.kt
  app/src/test/java/com/vaultionizer/vaultapp/model/data/FileCacheTest.kt
Labels: enhancement

#57 VAULTIONIZER-204: Implement file status overview
  .idea/compiler.xml
  .idea/misc.xml
  app/src/main/java/com/vaultionizer/vaultapp/repository/impl/FileRepositoryImpl.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/file/FileFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/status/FileStatusFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/status/FileStatusListAdapter.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/status/FileWorkerStatusPair.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/viewmodel/FileStatusViewModel.kt
  app/src/main/java/com/vaultionizer/vaultapp/util/Constants.kt
  app/src/main/java/com/vaultionizer/vaultapp/util/StringUtil.kt
  app/src/main/res/layout/fragment_file.xml
  app/src/main/res/layout/fragment_file_list.xml
  app/src/main/res/layout/fragment_file_status.xml
  app/src/main/res/layout/fragment_file_status_item.xml
  app/src/main/res/navigation/nav_main.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#62 VAULTIONIZER-242 Refactor caching possibilities in repositories.
  app/src/main/java/com/vaultionizer/vaultapp/data/model/domain/VNSpace.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/model/rest/result/ApiResult.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/model/rest/result/NetworkBoundResource.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/model/rest/result/Resource.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/AuthRepository.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/FileRepository.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/MiscRepository.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/ReferenceFileRepository.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/SpaceRepository.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/impl/AuthRepositoryImpl.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/impl/FileRepositoryImpl.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/impl/MiscRepositoryImpl.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/impl/ReferenceFileRepositoryImpl.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/impl/SpaceRepositoryImpl.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/auth/data/AuthEvent.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/auth/data/AuthViewModel.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/auth/login/LoginFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/auth/parts/alternative/RegisterSignUpAlternativeFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/auth/parts/input/HostInputFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/auth/parts/input/UserDataInputFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/auth/register/RegisterStepAuthKeyFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/auth/register/RegisterStepHostFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/auth/register/RegisterStepUserFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/viewmodel/CreateSpaceViewModel.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/viewmodel/MainActivityViewModel.kt
  app/src/main/java/com/vaultionizer/vaultapp/util/AuthUtil.kt
  app/src/main/java/com/vaultionizer/vaultapp/util/extension/FlowExtensions.kt
  app/src/main/java/com/vaultionizer/vaultapp/worker/FileUploadWorker.kt
  app/src/main/java/com/vaultionizer/vaultapp/worker/ReferenceFileSyncWorker.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/vaultionizer/vaultapp/model/data/FileCacheTest.kt
Labels: enhancement

#63 VAULTIONIZER-225 Integrate encryption into upload functions.
  app/src/main/java/com/vaultionizer/vaultapp/cryptography/Cryptography.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/db/entity/LocalFileSyncRequest.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/model/domain/VNSpace.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/model/rest/result/Resource.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/impl/FileRepositoryImpl.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/MainActivity.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/file/FileAlertDialogType.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/file/FileDialogState.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/file/FileEvent.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/file/FileFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/file/FileViewState.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/viewmodel/CreateSpaceViewModel.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/viewmodel/MainActivityViewModel.kt
  app/src/main/java/com/vaultionizer/vaultapp/worker/DataEncryptionWorker.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#61 Implemented settings UI.
  app/src/main/java/com/vaultionizer/vaultapp/data/db/dao/LocalFileDao.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/db/dao/LocalSpaceDao.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/db/dao/LocalUserDao.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/AuthRepository.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/FileRepository.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/SpaceRepository.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/impl/AuthRepositoryImpl.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/impl/FileRepositoryImpl.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/impl/SpaceRepositoryImpl.kt
  app/src/main/java/com/vaultionizer/vaultapp/service/UserService.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/auth/AuthenticationActivity.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/auth/welcome/WelcomeFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/MainActivity.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/file/FileAlertDialogType.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/settings/SettingsFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/viewmodel/SettingsViewModel.kt
  app/src/main/res/navigation/nav_main.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/fragment_settings.xml
Labels: enhancement

#68 Fix wrong id caching strategy for root folder.
  app/src/main/java/com/vaultionizer/vaultapp/data/cache/FileCache.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/impl/FileRepositoryImpl.kt
Labels: enhancement

#69 Add network status indicator if device is not connected.
  app/src/main/java/com/vaultionizer/vaultapp/VaultionizerApplication.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/live/NetworkLiveData.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/model/pc/PCCategory.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/model/pc/PCFile.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/model/pc/PCPair.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/PCRepository.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/impl/PCRepositoryImpl.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/file/FileFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/pc/ViewPCFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/pc/ViewPCItemClickListener.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/pc/ViewPCRecyclerViewAdapter.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/viewmodel/MainActivityViewModel.kt
  app/src/main/res/layout/fragment_file_list.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#71 Fix byte cut-off for decryption.
  app/src/main/java/com/vaultionizer/vaultapp/cryptography/Cryptography.kt
Labels: enhancement

#72 VAULTIONIZER-258: Finally remove upload file size limit.
  app/src/main/java/com/vaultionizer/vaultapp/data/db/entity/LocalFileSyncRequest.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/FileRepository.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/SyncRequestRepository.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/impl/FileRepositoryImpl.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/impl/SyncRequestRepositoryImpl.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/file/viewer/TextFileViewerFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/viewmodel/FileStatusViewModel.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/viewmodel/MainActivityViewModel.kt
  app/src/main/java/com/vaultionizer/vaultapp/util/Constants.kt
  app/src/main/java/com/vaultionizer/vaultapp/util/FileUtil.kt
  app/src/main/java/com/vaultionizer/vaultapp/worker/DataEncryptionWorker.kt
  app/src/main/java/com/vaultionizer/vaultapp/worker/FileUploadWorker.kt
Labels: enhancement

#75 Fix a bug that used the padder
  app/src/main/java/com/vaultionizer/vaultapp/cryptography/CryptoUtils.kt
Labels: enhancement

#74 VAULTIONIZER-257: Implement ReferenceFile encryption/decryption.
  .gitignore
  app/src/main/java/com/vaultionizer/vaultapp/data/db/VaultionizerLocalDatabase.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/db/dao/LocalSpaceDao.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/model/rest/result/ApiCallFactory.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/model/rest/result/ApiResultAdapter.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/model/rest/result/ApiResultCallDecorator.kt
  app/src/main/java/com/vaultionizer/vaultapp/hilt/RestModule.kt
  app/src/main/java/com/vaultionizer/vaultapp/hilt/interceptor/ReferenceFileCryptoInterceptor.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/SpaceRepository.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/impl/AuthRepositoryImpl.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/impl/SpaceRepositoryImpl.kt
Labels: enhancement

#76 VAULTIONIZER-254: Implement file updates.
  app/src/main/java/com/vaultionizer/vaultapp/data/model/domain/VNFile.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/FileRepository.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/impl/FileRepositoryImpl.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/file/FileAlertDialogType.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/file/FileBottomSheetOption.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/file/FileEvent.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/file/FileFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/viewmodel/MainActivityViewModel.kt
  app/src/main/java/com/vaultionizer/vaultapp/util/FileUtil.kt
  app/src/main/java/com/vaultionizer/vaultapp/worker/FileUploadWorker.kt
  app/src/main/res/layout/fragment_file_list.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#77 FileRepository refactorings and run auto-format for all files.
  app/src/main/java/com/vaultionizer/vaultapp/container-v1.schema.json
  app/src/main/java/com/vaultionizer/vaultapp/cryptography/CryptoClass.kt
  app/src/main/java/com/vaultionizer/vaultapp/cryptography/CryptoUtils.kt
  app/src/main/java/com/vaultionizer/vaultapp/cryptography/Cryptography.kt
  app/src/main/java/com/vaultionizer/vaultapp/cryptography/Hashing.kt
  app/src/main/java/com/vaultionizer/vaultapp/cryptography/PasswordValidator.kt
  app/src/main/java/com/vaultionizer/vaultapp/cryptography/model/Hash.kt
  app/src/main/java/com/vaultionizer/vaultapp/cryptography/model/Password.kt
  app/src/main/java/com/vaultionizer/vaultapp/cryptography/model/Salt.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/db/dao/LocalUserDao.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/model/domain/VNFile.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/model/pc/PCFile.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/model/rest/refFile/NetworkReferenceFile.kt
  app/src/main/java/com/vaultionizer/vaultapp/hilt/DatabaseModule.kt
  app/src/main/java/com/vaultionizer/vaultapp/hilt/RestModule.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/AuthRepository.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/impl/AuthRepositoryImpl.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/impl/FileRepositoryImpl.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/impl/ReferenceFileRepositoryImpl.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/impl/SpaceRepositoryImpl.kt
  app/src/main/java/com/vaultionizer/vaultapp/service/SessionService.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/auth/AuthenticationActivity.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/auth/data/AuthViewModel.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/auth/login/LoginFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/auth/parts/input/HostInputFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/auth/parts/input/UserDataInputFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/auth/register/RegisterStepHostFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/auth/welcome/WelcomeFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/MainActivity.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/file/FileAlertDialogType.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/file/FileRecyclerAdapter.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/keys/KeyManagementFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/qr_scanner/QRCodeScanFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/settings/SettingsFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/space/AuthKeyFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/space/CreateSpaceFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/space/SpacePermissionsFragment.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/viewmodel/CreateSpaceViewModel.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/viewmodel/MainActivityViewModel.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/viewmodel/ManageSpaceViewModel.kt
  app/src/main/java/com/vaultionizer/vaultapp/util/AuthKeyGen.kt
  app/src/main/java/com/vaultionizer/vaultapp/util/FileUtil.kt
  app/src/main/java/com/vaultionizer/vaultapp/util/WorkerUtil.kt
  app/src/main/java/com/vaultionizer/vaultapp/util/extension/FileExtensions.kt
  app/src/main/java/com/vaultionizer/vaultapp/util/extension/RestExtension.kt
  app/src/main/java/com/vaultionizer/vaultapp/util/external/RuntimeTypeAdapterFactory.java
  app/src/main/java/com/vaultionizer/vaultapp/util/qr/CRC32Handler.kt
  app/src/main/java/com/vaultionizer/vaultapp/util/qr/QRCodeGen.kt
  app/src/main/java/com/vaultionizer/vaultapp/worker/DataDecryptionWorker.kt
  app/src/main/java/com/vaultionizer/vaultapp/worker/DataEncryptionWorker.kt
  app/src/main/java/com/vaultionizer/vaultapp/worker/FileDownloadWorker.kt
  app/src/main/java/com/vaultionizer/vaultapp/worker/FileUploadWorker.kt
Labels: enhancement

#103 Refactor classes to object in crypto.
  app/src/androidTest/java/com/vaultionizer/vaultapp/cryptography/AesCbcNopaddingTest.kt
  app/src/main/java/com/vaultionizer/vaultapp/cryptography/AesCbcNopadding.kt
  app/src/main/java/com/vaultionizer/vaultapp/cryptography/AesGcmNopadding.kt
  app/src/main/java/com/vaultionizer/vaultapp/cryptography/CryptoClass.kt
  app/src/main/java/com/vaultionizer/vaultapp/cryptography/CryptoUtils.kt
  app/src/main/java/com/vaultionizer/vaultapp/cryptography/Cryptography.kt
  app/src/main/java/com/vaultionizer/vaultapp/cryptography/Hashing.kt
Labels: refactoring

#110 This commit will:
  app/src/androidTest/java/com/vaultionizer/vaultapp/cryptography/AesCbcNopaddingTest.kt
  app/src/androidTest/java/com/vaultionizer/vaultapp/cryptography/AesGcmNopaddingTest.kt
  app/src/androidTest/java/com/vaultionizer/vaultapp/cryptography/CryptographyTest.kt
  app/src/androidTest/java/com/vaultionizer/vaultapp/cryptography/HashingTest.kt
  app/src/main/java/com/vaultionizer/vaultapp/cryptography/CryptoUtils.kt
Labels: documentation

#113 Add JaCoCo support to SonarCloud.
  .github/workflows/sonarqube.yml
  app/build.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: testing

#114 Fix missing coverage information for SonarCloud.
  .github/workflows/pull_request_validation.yml
  app/build.gradle
  build.gradle
Labels: enhancement

#117 Fix AesCbCNoPadding
  app/src/main/java/com/vaultionizer/vaultapp/cryptography/AesCbcNopadding.kt
Labels: bug

#118 Decrease cognitive complexity.
  app/build.gradle
  app/src/main/java/com/vaultionizer/vaultapp/data/cache/DecryptionResultCache.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/auth/data/AuthViewModel.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/MainActivity.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/viewmodel/MainActivityViewModel.kt
Labels: enhancement

#119 Refactor code for better metrics.
  app/src/main/java/com/vaultionizer/vaultapp/cryptography/AesCbcNopadding.kt
  app/src/main/java/com/vaultionizer/vaultapp/cryptography/AesGcmNopadding.kt
  app/src/main/java/com/vaultionizer/vaultapp/cryptography/CryptoClass.kt
  app/src/main/java/com/vaultionizer/vaultapp/cryptography/Cryptography.kt
Labels: enhancement, refactoring

#73 VAULTIONIZER-259: Improve code documentation.
  app/src/main/java/com/vaultionizer/vaultapp/repository/AuthRepository.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/FileRepository.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/MiscRepository.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/impl/FileRepositoryImpl.kt
  app/src/main/java/com/vaultionizer/vaultapp/service/FileExchangeService.kt
  app/src/main/java/com/vaultionizer/vaultapp/service/FileService.kt
  app/src/main/java/com/vaultionizer/vaultapp/service/MiscService.kt
  app/src/main/java/com/vaultionizer/vaultapp/service/ReferenceFileService.kt
  app/src/main/java/com/vaultionizer/vaultapp/service/SessionService.kt
  app/src/main/java/com/vaultionizer/vaultapp/service/SpaceService.kt
  app/src/main/java/com/vaultionizer/vaultapp/service/UserService.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/viewmodel/MainActivityViewModel.kt
Labels: DO NOT MERGE, documentation

#120 Fix wrong method call in MainActivity.
  app/src/main/java/com/vaultionizer/vaultapp/ui/auth/data/AuthViewModel.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/main/MainActivity.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/viewmodel/MainActivityViewModel.kt
Labels: enhancement

#121 Improvement/server auth register
  .idea/codeStyles/Project.xml
  .idea/misc.xml
  app/src/main/java/com/vaultionizer/vaultapp/data/model/rest/misc/NetworkVersion.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/model/rest/request/ValidateAuthKeyRequest.kt
  app/src/main/java/com/vaultionizer/vaultapp/data/model/rest/result/Resource.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/MiscRepository.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/impl/AuthRepositoryImpl.kt
  app/src/main/java/com/vaultionizer/vaultapp/repository/impl/MiscRepositoryImpl.kt
  app/src/main/java/com/vaultionizer/vaultapp/service/MiscService.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/auth/data/AuthEvent.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/auth/data/AuthViewModel.kt
  app/src/main/java/com/vaultionizer/vaultapp/ui/auth/register/RegisterStepAuthKeyFragment.kt
  app/src/main/res/layout/fragment_register_step_auth_key.xml
Labels: enhancement

#122 Remove build step from workflow to speed-up overall execution time.
  .github/workflows/sonarqube.yml
Labels: enhancement
